---
# Variable setup.
- name: Include version-specific variables for Redhat/Centos.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution|title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Debian'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure {{ service_name }} service is running as configured.
  service:
    name: "{{ service_name }}"
    state: "{{ service_service_state }}"
    enabled: "{{ service_service_enabled }}"
