---
- name: Create a directory plugins if it does not exist
  file:
    path: "{{ grafana_data_dir }}/plugins"
    state: directory

- name: Check which plugins are installed
  command: "ls {{ grafana_data_dir }}/plugins"
  register: installed_plugins
  changed_when: false
  when: grafana_plugins is defined

- name: set grafana_plugins
  set_fact:
    grafana_plugins_ne: "{{ grafana_plugins | difference(installed_plugins.stdout_lines) }}"

- debug:
    var: grafana_plugins

- name: Install plugins
  become: true
  command: "grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins_ne }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart {{ service_name }}
  when: grafana_plugins_ne is defined
